ci: Enable cri-containerd-tests for arm64
This change enables cri-containerd-test for arm64.

Signed-off-by: Seunguk Shin <seunguk.shin@arm.com>
Reviewed-by: Nick Connolly <nick.connolly@arm.com>

diff --git a/.github/workflows/run-cri-containerd-tests.yaml b/.github/workflows/run-cri-containerd-tests.yaml
--- a/.github/workflows/run-cri-containerd-tests.yaml
+++ b/.github/workflows/run-cri-containerd-tests.yaml
@@ -42,6 +42,24 @@ jobs:
       GOPATH: ${{ github.workspace }}
       KATA_HYPERVISOR: ${{ inputs.vmm }}
     steps:
+      - name: Clean up workspace
+        if: ${{ inputs.arch == 'arm64' }}
+        run: |
+          if [ -z "${GITHUB_WORKSPACE}" ]; then
+            echo "ERROR: GITHUB_WORKSPACE is not set"
+            exit 1
+          fi
+
+          workspace_dir=$(sudo realpath "$GITHUB_WORKSPACE")
+          runner_base_dir=/home/github-runner/actions-runner/_work
+
+          if [[ $workspace_dir == $runner_base_dir* ]]; then
+            sudo find $GITHUB_WORKSPACE -mindepth 1 -delete
+          else
+            echo "ERROR: GITHUB_WORKSPACE ($GITHUB_WORKSPACE) must be within $runner_base_dir"
+            exit 1
+          fi
+
       - uses: actions/checkout@v4
         with:
           ref: ${{ inputs.commit-hash }}
